### ISSUE TITLE
「校对中」1. Introduction to iOS 11, Xcode 9 and Swift 4

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-11-Apps-with-Swift#1]
|条数|翻译|
|--:|--|
|1-288|@ApolloZhu|
|289~589|@SilkSong|
|590-1501|@ApolloZhu|
|1502-1620|@SilkSong|

**Comment by SilkSong** [comment]
翻译：300段   289~589

**Comment by ApolloZhu** [comment]
@SilkSong 是从259 到多少？

**Comment by SilkSong** [comment]
翻译：1500~1620
预计时间: 北京时间周五24点

**Comment by ApolloZhu** [comment]
@SilkSong 好的，麻烦了

**Comment by ApolloZhu** [comment]
注意是 1502 开始

**Comment by LiulietLee** [comment]
校对 (°∀°)ﾉ

**Comment by ApolloZhu** [comment]
好

Sent from my iPhone

On Nov 18, 2017, at 20:00, Liuliet.Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


校对 (°∀°)ﾉ
