### ISSUE TITLE
「任务分配」7. Multiple MVCs, Timer, and Animation

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-11-Apps-with-Swift#12]
4 - 300 @smilexyk 
301 - ... - 1493

**Comment by smilexyk** [comment]
想认领，请问有什么要求？

**Comment by LiulietLee** [comment]
@smilexyk https://github.com/ApolloZhu/Developing-iOS-11-Apps-with-Swift/blob/master/CONTRIBUTING.md

**Comment by smilexyk** [comment]
OK，我这里已经将完整project fork到我的个人项目上。第一次做这个项目，先认领4-300行吧。预计完成时间本周末。

**Comment by ApolloZhu** [comment]
Thanks

**Comment by ApolloZhu** [comment]
暂时优先 3-5
