### ISSUE TITLE
「校对中」2. MVC

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-11-Apps-with-Swift#2]
4-399 @ApolloZhu
400-800 @SilkSong 
801-1198 @ApolloZhu
1198-1316 @SilkSong

----

这一集的 green arrow 在 iOS 10 的翻译中有译为“绿色通道” 的情况，正好能对上官方把 outlet 翻译成出口，可以酌情使用

**Comment by ApolloZhu** [comment]
待校对：
391 semantic 请根据后文判断是否应该翻译为语义
semantic: meaning in language or logic.

**Comment by SilkSong** [comment]
翻译：400~800段

**Comment by ApolloZhu** [comment]
好的

**Comment by ApolloZhu** [comment]
注：[CountableRange](https://developer.apple.com/documentation/swift/countablerange) 为类名

**Comment by ApolloZhu** [comment]
@SilkSong 注意对照视频，那个是 wired up 而不是 fired up

**Comment by SilkSong** [comment]
好的，翻译已完成，我先 commit 到自己仓库，所以翻译完成后再 pull request 就好, 是吧

**Comment by ApolloZhu** [comment]
诶，是的

**Comment by SilkSong** [comment]
翻译：1199~1316

**Comment by ApolloZhu** [comment]
好的

**Comment by LiulietLee** [comment]
先来占个校对的坑 (°∀°)ﾉ

**Comment by ApolloZhu** [comment]
509 太长了，弹幕传不上去...以后得控制长度

**Comment by SilkSong** [comment]
好的
