### ISSUE TITLE
求分享课件 PPT 和相关资料，辛苦各位大大

### ISSUE THREAD

**Issue by guofeng007** [ApolloZhu/Developing-iOS-11-Apps-with-Swift#23]
- [ ] 请先查看 [常见问题与解答](../SUPPORT.md)
如标题：求分享课件 PPT 和相关资料，辛苦各位大大

**Comment by guofeng007** [comment]
打包上传网盘了链接: https://pan.baidu.com/s/1k-9MJcYTzyCMrJg04h2vrQ 密码: 546w

**Comment by ApolloZhu** [comment]
上面写的是 iOS 10...
iOS 11 换了很多内容：https://github.com/ApolloZhu/Developing-iOS-11-Apps-with-Swift/blob/master/tools/update/download.md

**Comment by crazygit** [comment]
我整理了下从iTunes U上面下载视频的高清地址，可以直接下载高清视频
https://www.v2ex.com/t/457681
