### ISSUE TITLE
「任务分配」3. Swift Programming Language

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-11-Apps-with-Swift#3]
|条数|翻译|校对|
|-:|--|--|
|1-121|@SilkSong|@ApolloZhu|
|122-800|@SilkSong|@ApolloZhu|
|801-1627|@ApolloZhu|@ApolloZhu|

校对请使用 review-ep-3 分支

**Comment by SilkSong** [comment]
翻译：1~800

**Comment by ApolloZhu** [comment]
好

Sent from my iPhone

On Nov 22, 2017, at 03:44, Zixin SONG <notifications@github.com<mailto:notifications@github.com>> wrote:


翻译：1~800

**Comment by ApolloZhu** [comment]
我，1102-1627，24 小时内

**Comment by ApolloZhu** [comment]
@LiulietLee 有空校对一下？

**Comment by LiulietLee** [comment]
吼啊
