### ISSUE TITLE
如何设置中文字幕

### ISSUE THREAD

**Issue by LittleEasy** [ApolloZhu/Developing-iOS-11-Apps-with-Swift#36]
- [ ] 请先查看 [常见问题与解答](../SUPPORT.md)
1.指定播放器已经下载并安装好了
2.subtitles 文件夹中是中英字幕 也下载好了
然后怎么观看视屏呢？ subtitles里只有.srt文件，不能直接观看啊。是需要下载视屏在配合.srt文件观看吗？求指教。谢谢！

**Comment by ApolloZhu** [comment]
可以通过 iTunes U 或 Podcasts 下载，或者在线观看：https://www.bilibili.com/video/av16339375/

**Comment by LittleEasy** [comment]
按照您的提示已经可以正常观看视屏。在此非常感谢您的仗义相助，愿您身心健康！
